[project]
name = 'Transparent-Government-Procurement-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bid-submission]
path = 'contracts/bid-submission.clar'
clarity_version = 2
epoch = 2.5

[contracts.contract-fulfillment]
path = 'contracts/contract-fulfillment.clar'
clarity_version = 2
epoch = 2.5

[contracts.vendor-registration]
path = 'contracts/vendor-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
